# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'dictSelect.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt


class Widget_Dict_Select(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sw_dictSelectMange = QtWidgets.QStackedWidget(self.centralwidget)
        self.sw_dictSelectMange.setObjectName("sw_dictSelectMange")

        self.gridLayout.addWidget(self.sw_dictSelectMange, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.tb_equipHandbook = QtWidgets.QToolButton(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/handbook.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_equipHandbook.setIcon(icon1)
        self.tb_equipHandbook.setObjectName("tb_equipHandbook")
        self.tb_equipHandbook.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.tb_factoryDict = QtWidgets.QToolButton(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/factory.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_factoryDict.setIcon(icon2)
        self.tb_factoryDict.setObjectName("tb_factoryDict")
        self.tb_factoryDict.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.tb_presentRoom = QtWidgets.QToolButton(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/room.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_presentRoom.setIcon(icon3)
        self.tb_presentRoom.setObjectName("tb_presentRoom")
        self.tb_presentRoom.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.tb_regularManage = QtWidgets.QToolButton(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/regular.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_regularManage.setIcon(icon4)
        self.tb_regularManage.setObjectName("tb_regularManage")
        self.tb_regularManage.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.toolBar.addWidget(self.tb_equipHandbook)
        self.toolBar.addWidget(self.tb_factoryDict)
        self.toolBar.addWidget(self.tb_presentRoom)
        self.toolBar.addWidget(self.tb_regularManage)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.tb_equipHandbook.setText(_translate("MainWindow", "装备性能手册"))
        self.tb_factoryDict.setText(_translate("MainWindow", "厂家目录"))
        self.tb_presentRoom.setText(_translate("MainWindow", "代表室目录"))
        self.tb_regularManage.setText(_translate("MainWindow", "法规管理"))

import icons.resource_rc