# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'regularManage.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Widget_Regular_Manage(object):
    def setupUi(self, widget):
        widget.setObjectName("widget")
        widget.resize(1053, 806)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(widget)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(10, -1, 10, -1)
        self.horizontalLayout_2.setSpacing(10)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.label = QtWidgets.QLabel(widget)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.le_fileName = QtWidgets.QLineEdit(widget)
        self.le_fileName.setMinimumSize(QtCore.QSize(150, 30))
        self.le_fileName.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.le_fileName.setObjectName("le_fileName")
        self.horizontalLayout_2.addWidget(self.le_fileName)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.pb_search = QtWidgets.QPushButton(widget)
        self.pb_search.setMinimumSize(QtCore.QSize(40, 0))
        self.pb_search.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pb_search.setObjectName("pb_search")
        self.horizontalLayout_2.addWidget(self.pb_search)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem2)
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 2)
        self.horizontalLayout_2.setStretch(2, 8)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 3)
        self.horizontalLayout_2.setStretch(5, 1)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.lw_file = QtWidgets.QTableWidget(widget)
        self.lw_file.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.lw_file.setDragEnabled(True)
        self.lw_file.setObjectName("lw_file")
        self.lw_file.setColumnCount(0)
        self.lw_file.setRowCount(0)
        self.verticalLayout.addWidget(self.lw_file)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pb_input = QtWidgets.QPushButton(widget)
        self.pb_input.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pb_input.setObjectName("pb_input")
        self.horizontalLayout.addWidget(self.pb_input)
        self.pb_delete = QtWidgets.QPushButton(widget)
        self.pb_delete.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pb_delete.setObjectName("pb_delete")
        self.horizontalLayout.addWidget(self.pb_delete)
        self.pb_output = QtWidgets.QPushButton(widget)
        self.pb_output.setMaximumSize(QtCore.QSize(150, 16777215))
        self.pb_output.setObjectName("pb_output")
        self.horizontalLayout.addWidget(self.pb_output)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.verticalLayout_2.addLayout(self.verticalLayout)

        self.retranslateUi(widget)
        QtCore.QMetaObject.connectSlotsByName(widget)

    def retranslateUi(self, widget):
        _translate = QtCore.QCoreApplication.translate
        widget.setWindowTitle(_translate("widget", "法规管理"))
        self.label.setText(_translate("widget", "搜索法规文件："))
        self.pb_search.setText(_translate("widget", "搜索"))
        self.pb_input.setText(_translate("widget", "导入法规"))
        self.pb_delete.setText(_translate("widget", "删除法规"))
        self.pb_output.setText(_translate("widget", "导出法规"))
