# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StrengthDisturb.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets,Qt

#new
class ContractManagementMainUI(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.tb_orderManagement = QtWidgets.QToolButton(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/orderManagement.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_orderManagement.setIcon(icon)
        self.tb_orderManagement.setObjectName("tb_orderManagement")
        self.tb_orderManagement.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.tb_maintenanceManagement = QtWidgets.QToolButton(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/maintenanceManagement.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_maintenanceManagement.setIcon(icon1)
        self.tb_maintenanceManagement.setObjectName("tb_maintenanceManagement")
        self.tb_maintenanceManagement.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)


        self.toolBar.addWidget(self.tb_orderManagement)
        self.toolBar.addWidget(self.tb_maintenanceManagement)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.tb_orderManagement.setText(_translate("MainWindow", "订单合同"))
        self.tb_maintenanceManagement.setText(_translate("MainWindow", "维修合同"))

import icons.resource_rc
