# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooseFactoryYear.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class widget_chooseFactoryYear(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 300)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb_factoryYear = QtWidgets.QComboBox(Dialog)
        self.cb_factoryYear.setObjectName("cb_factoryYear")
        self.horizontalLayout.addWidget(self.cb_factoryYear)
        self.horizontalLayout.setStretch(0, 3)
        self.horizontalLayout.setStretch(1, 7)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.tb_yes = QtWidgets.QToolButton(Dialog)
        self.tb_yes.setObjectName("tb_yes")
        self.horizontalLayout_2.addWidget(self.tb_yes)
        self.tb_cancel = QtWidgets.QToolButton(Dialog)
        self.tb_cancel.setObjectName("tb_cancel")
        self.horizontalLayout_2.addWidget(self.tb_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.verticalLayout.setStretch(0, 7)
        self.verticalLayout.setStretch(1, 3)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "出厂年份选择："))
        self.tb_yes.setText(_translate("Dialog", "确定"))
        self.tb_cancel.setText(_translate("Dialog", "取消"))
