# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'chooseFactoryYear.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class widget_chooseFactoryYear(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(419, 300)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setObjectName("gridLayout")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.cb_seeMethod = QtWidgets.QComboBox(Dialog)
        self.cb_seeMethod.setObjectName("cb_seeMethod")
        self.cb_seeMethod.addItem("")
        self.cb_seeMethod.addItem("")
        self.horizontalLayout_3.addWidget(self.cb_seeMethod)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_3.addItem(spacerItem)
        self.gridLayout.addLayout(self.horizontalLayout_3, 0, 0, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(Dialog)
        self.groupBox.setObjectName("groupBox")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.groupBox)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.groupBox)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb_factoryYearStart = QtWidgets.QComboBox(self.groupBox)
        self.cb_factoryYearStart.setMinimumSize(QtCore.QSize(100, 0))
        self.cb_factoryYearStart.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cb_factoryYearStart.setObjectName("cb_factoryYearStart")
        self.horizontalLayout.addWidget(self.cb_factoryYearStart)
        self.label_2 = QtWidgets.QLabel(self.groupBox)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.cb_factoryYearEnd = QtWidgets.QComboBox(self.groupBox)
        self.cb_factoryYearEnd.setMinimumSize(QtCore.QSize(100, 0))
        self.cb_factoryYearEnd.setMaximumSize(QtCore.QSize(100, 16777215))
        self.cb_factoryYearEnd.setObjectName("cb_factoryYearEnd")
        self.horizontalLayout.addWidget(self.cb_factoryYearEnd)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.gridLayout.addWidget(self.groupBox, 1, 0, 1, 1)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem1)
        self.tb_yes = QtWidgets.QToolButton(Dialog)
        self.tb_yes.setObjectName("tb_yes")
        self.horizontalLayout_2.addWidget(self.tb_yes)
        self.tb_cancel = QtWidgets.QToolButton(Dialog)
        self.tb_cancel.setObjectName("tb_cancel")
        self.horizontalLayout_2.addWidget(self.tb_cancel)
        self.gridLayout.addLayout(self.horizontalLayout_2, 2, 0, 1, 1)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label_3.setText(_translate("Dialog", "查看方式："))
        self.cb_seeMethod.setItemText(0, _translate("Dialog", "全部"))
        self.cb_seeMethod.setItemText(1, _translate("Dialog", "按照年份范围查看"))
        self.groupBox.setTitle(_translate("Dialog", "选择出厂年份范围"))
        self.label.setText(_translate("Dialog", "出厂年份范围选择："))
        self.label_2.setText(_translate("Dialog", "至"))
        self.tb_yes.setText(_translate("Dialog", "确定"))
        self.tb_cancel.setText(_translate("Dialog", "取消"))
