# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'factoryYearSet.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

#new
from PyQt5 import QtCore, QtGui, QtWidgets


class Widget_Factory_Year_Set(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(866, 569)
        self.gridLayout_2 = QtWidgets.QGridLayout(Form)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.tw_yearSet = QtWidgets.QTableWidget(Form)
        self.tw_yearSet.setObjectName("tw_yearSet")
        self.tw_yearSet.setColumnCount(0)
        self.tw_yearSet.setRowCount(0)
        self.gridLayout_2.addWidget(self.tw_yearSet, 0, 0, 1, 1)
        self.gridLayout = QtWidgets.QGridLayout()
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(Form)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.le_yearID = QtWidgets.QLineEdit(Form)
        self.le_yearID.setObjectName("le_yearID")
        self.gridLayout.addWidget(self.le_yearID, 0, 2, 1, 1)
        self.pb_add = QtWidgets.QPushButton(Form)
        self.pb_add.setObjectName("pb_add")
        self.gridLayout.addWidget(self.pb_add, 0, 3, 1, 1)
        self.pb_update = QtWidgets.QPushButton(Form)
        self.pb_update.setObjectName("pb_update")
        self.gridLayout.addWidget(self.pb_update, 0, 4, 1, 1)
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.pb_input = QtWidgets.QPushButton(Form)
        self.pb_input.setObjectName("pb_input")
        self.gridLayout.addWidget(self.pb_input, 1, 4, 1, 1)
        self.pb_del = QtWidgets.QPushButton(Form)
        self.pb_del.setObjectName("pb_del")
        self.gridLayout.addWidget(self.pb_del, 1, 3, 1, 1)
        self.de_year = QtWidgets.QDateEdit(Form)
        self.de_year.setObjectName("de_year")
        self.gridLayout.addWidget(self.de_year, 1, 2, 1, 1)
        self.gridLayout_2.addLayout(self.gridLayout, 1, 0, 1, 1)

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "出厂年份编号："))
        self.pb_add.setText(_translate("Form", "新增"))
        self.pb_update.setText(_translate("Form", "修改"))
        self.label_2.setText(_translate("Form", "出厂年份："))
        self.pb_input.setText(_translate("Form", "导入"))
        self.pb_del.setText(_translate("Form", "删除"))
