# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'manage_widget.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

#new
class Widget_Manage_Widgets(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tb_ManageWidget = QtWidgets.QTabWidget(self.centralwidget)
        self.tb_ManageWidget.setObjectName("tb_ManageWidget")
        self.gridLayout.addWidget(self.tb_ManageWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.action_strenInquiry = QtWidgets.QAction(MainWindow)
        self.action_strenInquiry.setObjectName("action_strenInquiry")
        self.action_weaveMainten = QtWidgets.QAction(MainWindow)
        self.action_weaveMainten.setObjectName("action_weaveMainten")
        self.action_equipBalance = QtWidgets.QAction(MainWindow)
        self.action_equipBalance.setObjectName("action_equipBalance")
        self.action_applyRetire = QtWidgets.QAction(MainWindow)
        self.action_applyRetire.setObjectName("action_applyRetire")
        self.action_adjustPlan = QtWidgets.QAction(MainWindow)
        self.action_adjustPlan.setObjectName("action_adjustPlan")
        self.action_transferProgress = QtWidgets.QAction(MainWindow)
        self.action_transferProgress.setObjectName("action_transferProgress")
        self.action_orderManage = QtWidgets.QAction(MainWindow)
        self.action_orderManage.setObjectName("action_orderManage")

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.action_strenInquiry.setText(_translate("MainWindow", "实力查询"))
        self.action_weaveMainten.setText(_translate("MainWindow", "编制数维护"))
        self.action_equipBalance.setText(_translate("MainWindow", "装备平衡表"))
        self.action_applyRetire.setText(_translate("MainWindow", "申请退役"))
        self.action_adjustPlan.setText(_translate("MainWindow", "分配调整计划"))
        self.action_transferProgress.setText(_translate("MainWindow", "调拨进度"))
        self.action_orderManage.setText(_translate("MainWindow", "调拨单管理"))
