# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StrengthDisturb.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Strength_Disturb_Widget(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1000, 700)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setContextMenuPolicy(QtCore.Qt.PreventContextMenu)
        self.toolBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.toolBar.setToolButtonStyle(QtCore.Qt.ToolButtonTextUnderIcon)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)
        self.actionstrengthSelect = QtWidgets.QAction(MainWindow)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap(":/pic/select.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionstrengthSelect.setIcon(icon)
        self.actionstrengthSelect.setObjectName("actionstrengthSelect")
        self.actionmaintenMange = QtWidgets.QAction(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/wave.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionmaintenMange.setIcon(icon1)
        self.actionmaintenMange.setObjectName("actionmaintenMange")
        self.actionequipBalance = QtWidgets.QAction(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/equip.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionequipBalance.setIcon(icon2)
        self.actionequipBalance.setObjectName("actionequipBalance")
        self.actionapplyRetire = QtWidgets.QAction(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/retire.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionapplyRetire.setIcon(icon3)
        self.actionapplyRetire.setObjectName("actionapplyRetire")
        self.actionstrengthDisturbSet = QtWidgets.QAction(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/set.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.actionstrengthDisturbSet.setIcon(icon4)
        self.actionstrengthDisturbSet.setObjectName("actionstrengthDisturbSet")
        self.toolBar.addAction(self.actionstrengthSelect)
        self.toolBar.addAction(self.actionmaintenMange)
        self.toolBar.addAction(self.actionequipBalance)
        self.toolBar.addAction(self.actionapplyRetire)
        self.toolBar.addAction(self.actionstrengthDisturbSet)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.actionstrengthSelect.setText(_translate("MainWindow", "strengthSelect"))
        self.actionmaintenMange.setText(_translate("MainWindow", "maintenMange"))
        self.actionequipBalance.setText(_translate("MainWindow", "equipBalance"))
        self.actionapplyRetire.setText(_translate("MainWindow", "applyRetire"))
        self.actionstrengthDisturbSet.setText(_translate("MainWindow", "strengthDisturbSet"))
import icons.resource_rc
