# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget_OrderAdjustCont.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Widget_OrderAdjustCont(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(630, 529)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.contForm = QtWidgets.QTableWidget(Dialog)
        self.contForm.setObjectName("contForm")
        self.contForm.setColumnCount(0)
        self.contForm.setRowCount(0)
        self.verticalLayout.addWidget(self.contForm)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem)
        self.pb_Save = QtWidgets.QPushButton(Dialog)
        self.pb_Save.setObjectName("pb_Save")
        self.horizontalLayout_7.addWidget(self.pb_Save)
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem1)
        self.pb_Input = QtWidgets.QPushButton(Dialog)
        self.pb_Input.setObjectName("pb_Input")
        self.horizontalLayout_7.addWidget(self.pb_Input)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem2)
        self.pb_Output = QtWidgets.QPushButton(Dialog)
        self.pb_Output.setObjectName("pb_Output")
        self.horizontalLayout_7.addWidget(self.pb_Output)
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem3)
        self.verticalLayout.addLayout(self.horizontalLayout_7)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pb_Save.setText(_translate("Dialog", "保存"))
        self.pb_Input.setText(_translate("Dialog", "导入"))
        self.pb_Output.setText(_translate("Dialog", "导出"))
