# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Widget_SelectQua.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Widget_SelectQua(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(400, 217)
        Dialog.setMinimumSize(QtCore.QSize(400, 150))
        Dialog.setMaximumSize(QtCore.QSize(450, 250))
        self.pb_Yes = QtWidgets.QPushButton(Dialog)
        self.pb_Yes.setGeometry(QtCore.QRect(310, 170, 75, 23))
        self.pb_Yes.setObjectName("pb_Yes")
        self.layoutWidget = QtWidgets.QWidget(Dialog)
        self.layoutWidget.setGeometry(QtCore.QRect(30, 90, 331, 22))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.cb_selectQua = QtWidgets.QComboBox(self.layoutWidget)
        self.cb_selectQua.setObjectName("cb_selectQua")
        self.cb_selectQua.addItem("")
        self.cb_selectQua.addItem("")
        self.cb_selectQua.addItem("")
        self.cb_selectQua.addItem("")
        self.cb_selectQua.addItem("")
        self.horizontalLayout.addWidget(self.cb_selectQua)
        self.horizontalLayout.setStretch(0, 5)
        self.horizontalLayout.setStretch(1, 7)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pb_Yes.setText(_translate("Dialog", "确定"))
        self.label.setText(_translate("Dialog", "请选择装备质量："))
        self.cb_selectQua.setItemText(0, _translate("Dialog", "未选择"))
        self.cb_selectQua.setItemText(1, _translate("Dialog", "新品"))
        self.cb_selectQua.setItemText(2, _translate("Dialog", "堪用品"))
        self.cb_selectQua.setItemText(3, _translate("Dialog", "待维修"))
        self.cb_selectQua.setItemText(4, _translate("Dialog", "废品"))
