# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'addUnitChoose.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Widget_AddUnitChoose(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.setWindowModality(QtCore.Qt.NonModal)
        Dialog.resize(624, 524)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tb_unitChoose = QtWidgets.QTableWidget(Dialog)
        self.tb_unitChoose.setObjectName("tb_unitChoose")
        self.tb_unitChoose.setColumnCount(0)
        self.tb_unitChoose.setRowCount(0)
        self.verticalLayout.addWidget(self.tb_unitChoose)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_Yes = QtWidgets.QPushButton(Dialog)
        self.pb_Yes.setObjectName("pb_Yes")
        self.horizontalLayout.addWidget(self.pb_Yes)
        self.pb_cancel = QtWidgets.QPushButton(Dialog)
        self.pb_cancel.setObjectName("pb_cancel")
        self.horizontalLayout.addWidget(self.pb_cancel)
        self.verticalLayout.addLayout(self.horizontalLayout)

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "单位目录选择"))
        self.pb_Yes.setText(_translate("Dialog", "确定"))
        self.pb_cancel.setText(_translate("Dialog", "返回"))
