# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'alocatMange.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets,Qt


class Widget_Alocat_Mange(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 614)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setObjectName("stackedWidget")
        self.gridLayout.addWidget(self.stackedWidget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)

        self.tb_disturbPlan = QtWidgets.QToolButton(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/plan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_disturbPlan.setIcon(icon1)
        self.tb_disturbPlan.setObjectName("tb_disturbPlan")
        self.tb_disturbPlan.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.tb_disturbSchedule = QtWidgets.QToolButton(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/schedule.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_disturbSchedule.setIcon(icon2)
        self.tb_disturbSchedule.setObjectName("tb_disturbSchedule")
        self.tb_disturbSchedule.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.tb_disturbManage = QtWidgets.QToolButton(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/manage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_disturbManage.setIcon(icon3)
        self.tb_disturbManage.setObjectName("tb_disturbManage")
        self.tb_disturbManage.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.tb_alocatSet = QtWidgets.QToolButton(MainWindow)
        icon4 = QtGui.QIcon()
        icon4.addPixmap(QtGui.QPixmap(":/pic/set.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_alocatSet.setIcon(icon4)
        self.tb_alocatSet.setObjectName("tb_alocatSet")
        self.tb_alocatSet.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.toolBar.addWidget(self.tb_disturbPlan)
        self.toolBar.addWidget(self.tb_disturbSchedule)
        self.toolBar.addWidget(self.tb_disturbManage)
        self.toolBar.addWidget(self.tb_alocatSet)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)



    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.tb_disturbPlan.setText(_translate("MainWindow", "分配调整计划"))
        self.tb_disturbSchedule.setText(_translate("MainWindow", "调拨进度"))
        self.tb_disturbManage.setText(_translate("MainWindow", "调拨单管理"))
        self.tb_alocatSet.setText(_translate("MainWindow", "调配管理设置"))

import icons.resource_rc

