# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transferManage.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets, Qt

#new
class Widget_Transfer_Manage(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1072, 723)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.sw_manageWIdget = QtWidgets.QStackedWidget(self.centralwidget)
        self.sw_manageWIdget.setObjectName("sw_manageWIdget")
        self.gridLayout.addWidget(self.sw_manageWIdget, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.RightToolBarArea, self.toolBar)

        self.tb_armyTransfer = QtWidgets.QToolButton(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/army.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_armyTransfer.setIcon(icon1)
        self.tb_armyTransfer.setObjectName("tb_armyTransfer")
        self.tb_armyTransfer.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.tb_rocketTransfer = QtWidgets.QToolButton(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/rocket.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_rocketTransfer.setIcon(icon2)
        self.tb_rocketTransfer.setObjectName("tb_rocketTransfer")
        self.tb_rocketTransfer.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.toolBar.addWidget(self.tb_armyTransfer)
        self.toolBar.addWidget(self.tb_rocketTransfer)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.tb_armyTransfer.setText(_translate("MainWindow", "陆军调拨单"))
        self.tb_rocketTransfer.setText(_translate("MainWindow", "火箭军调拨单"))