# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'transferModel.ui'
#
# Created by: PyQt5 UI code generator 5.15.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Widget_Transfer_Model(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1203, 828)
        self.gridLayout = QtWidgets.QGridLayout(Dialog)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(0)
        self.gridLayout.setObjectName("gridLayout")
        self.tw_transferModel = QtWidgets.QTabWidget(Dialog)
        self.tw_transferModel.setTabPosition(QtWidgets.QTabWidget.South)
        self.tw_transferModel.setObjectName("tw_transferModel")
        self.gridLayout.addWidget(self.tw_transferModel, 0, 0, 1, 1)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.pb_confirm = QtWidgets.QPushButton(Dialog)
        self.pb_confirm.setObjectName("pb_confirm")
        self.horizontalLayout.addWidget(self.pb_confirm)
        self.pb_saveTotal = QtWidgets.QPushButton(Dialog)
        self.pb_saveTotal.setObjectName("pb_saveTotal")
        self.horizontalLayout.addWidget(self.pb_saveTotal)
        self.pb_input = QtWidgets.QPushButton(Dialog)
        self.pb_input.setObjectName("pb_input")
        self.horizontalLayout.addWidget(self.pb_input)
        self.pb_output = QtWidgets.QPushButton(Dialog)
        self.pb_output.setObjectName("pb_output")
        self.horizontalLayout.addWidget(self.pb_output)
        self.gridLayout.addLayout(self.horizontalLayout, 1, 0, 1, 1)

        self.retranslateUi(Dialog)
        self.tw_transferModel.setCurrentIndex(-1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.pb_confirm.setText(_translate("Dialog", "确定"))
        self.pb_saveTotal.setText(_translate("Dialog", "保存总单"))
        self.pb_input.setText(_translate("Dialog", "导入"))
        self.pb_output.setText(_translate("Dialog", "导出"))
