# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'MaintainSupport.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets,Qt


class widget_MaintainSupport(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 571)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.sw_MaintainSup = QtWidgets.QStackedWidget(self.centralwidget)
        self.sw_MaintainSup.setObjectName("sw_MaintainSup")
        self.gridLayout.addWidget(self.sw_MaintainSup, 0, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 23))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.toolBar = QtWidgets.QToolBar(MainWindow)
        self.toolBar.setObjectName("toolBar")
        MainWindow.addToolBar(QtCore.Qt.TopToolBarArea, self.toolBar)


        self.tb_yearSerSup = QtWidgets.QToolButton(MainWindow)
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap(":/pic/plan.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_yearSerSup.setIcon(icon1)
        self.tb_yearSerSup.setObjectName("tb_yearSerSup")
        self.tb_yearSerSup.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.tb_maintainSchedule = QtWidgets.QToolButton(MainWindow)
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap(":/pic/schedule.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_maintainSchedule.setIcon(icon2)
        self.tb_maintainSchedule.setObjectName("tb_maintainSchedule")
        self.tb_maintainSchedule.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.tb_materialManage = QtWidgets.QToolButton(MainWindow)
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap(":/pic/manage.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.tb_materialManage.setIcon(icon3)
        self.tb_materialManage.setObjectName("tb_materialManage")
        self.tb_materialManage.setToolButtonStyle(Qt.Qt.ToolButtonTextUnderIcon)

        self.toolBar.addWidget(self.tb_yearSerSup)
        self.toolBar.addWidget(self.tb_maintainSchedule)
        self.toolBar.addWidget(self.tb_materialManage)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.toolBar.setWindowTitle(_translate("MainWindow", "toolBar"))
        self.tb_yearSerSup.setText(_translate("MainWindow", "维修计划"))
        self.tb_maintainSchedule.setText(_translate("MainWindow", "维修进度"))
        self.tb_materialManage.setText(_translate("MainWindow", "物资管理"))

